config/routes.rb
Munchable::Application.routes.draw do
  devise_for :users,
    :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout',
      :sign_up => 'signup'
    }

  
  root :to => "application#index"
  resources :restaurants do
    get 'instant', :on => :collection, :action => 'instant'
    get 'n_instant', :on => :collection, :action => 'name_instant'
  end
  resources :categories do
    get 'autocomplete', :on => :collection, :action => 'autocomplete'
  end
  resources :locations
  resources :users do
    resources :groups do
      resource :list do
        resources :listings
      end
    end
    resource :profile
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :list
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    @group = Group.find(params[:group_id])
    @restaurant = Restaurant.find(params[:rid])

    if Listing.where(:list_id => @group.list.id, :restaurant_id => @restaurant.id).empty?
      @listing = Listing.create({
        :list_id => @group.list.id,
        :restaurant_id => @restaurant.id
      })
    else
      flash[:notice] = 'Restaurant already exists!'
    end
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/views/listings/_listing.html.haml
.restaurant_listing.ui-state-default.ui-corner-all{:id => "listing-#{listing.id}"}
  %span{:class => 'ui-icon ui-icon-triangle-1-e', :style => 'float: left; padding: 1px'}
  = restaurant.name
  -# = link_to 'comment', ''
  %span{:style => 'float: right'}
    = form_tag user_group_list_listing_url(:user_id => @user.id, :group_id => @group.id, :id => listing.id), :remote => :true, :method => :delete do
      = submit_tag '', :style => "border: none", :class => 'ui-icon ui-icon-circle-close'