config/routes.rb
Munchable::Application.routes.draw do
  devise_for :users,
    :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout',
      :sign_up => 'signup'
    }

  
  root :to => "application#index"
  resources :restaurants do
    get 'instant', :on => :collection, :action => 'instant'
    get 'n_instant', :on => :collection, :action => 'name_instant'
  end
  resources :categories do
    get 'autocomplete', :on => :collection, :action => 'autocomplete'
  end
  resources :locations
  resources :users do
    resources :groups do
      resource :list do
        resources :listings
      end
    end
    resource :profile
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_one :list

  def members
    uids = self.memberships.all(:select => :user_id).collect {|m| m.user_id }.uniq
    User.all(:conditions => "id IN (#{uids.join(',')})")
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    @group = @user.create_group(params[:group_name])

    respond_to do |format|
      format.js
    end
  end

  def show
    @user = User.find(params[:user_id])
    @group = Group.find(params[:id])
    @list = @group.list

    @restaurant_listings = @list.listings.zip(@list.restaurants)
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/views/groups/_group.html.haml
.group_listing.ui-state-default.ui-corner-all{:id => "group-#{group.id}"}
  %span{:class => 'ui-icon ui-icon-triangle-1-e', :style => 'float: left; padding: 1px'}
  = link_to group.name, user_group_url(:id => group.id)
  %span{:style => 'float: right'}
    = form_tag user_group_url(:user_id => @user.id, :id => group.id), :remote => :true, :method => :delete do
      = submit_tag '', :style => "border: none", :class => 'ui-icon ui-icon-circle-close'

app/views/groups/show.html.haml
#group_page
  %h2 Group: #{@group.name}

  -#
    %p Members
    - for member in @group.members
      = member.email
    %p= link_to 'Add member', ''

  #listings
    %h3 Restaurants
    #restaurants
      - for r_listing in @restaurant_listings
        = render :partial => 'listings/listing', :locals => { :listing => r_listing[0], :restaurant => r_listing[1] }

    #search
      = form_tag user_group_list_listings_url(:user_id => @user.id, :group_id => @group.id), :method => :post, :remote => :true do
        = text_field_tag :q, params[:q], :id => 'restaurant_ac'
        = hidden_field_tag :rid, :id => 'rid'
        = submit_tag 'Add'

  #map{:style => 'float: right; width: 300px; height: 300px; border: 1px dotted black'}
  .clear

:javascript
  var query;
  var restaurant;
  var restaurant_data;
  var r_data;
  var r_names;

  function requestData(callback) {
    query = $("#restaurant_ac").val();
    $.getJSON('/restaurants/n_instant', { q: query }, function(data) {
        r_data = data.restaurants;
        r_names = [];
        for (i in r_data) {
          r_names.push(r_data[i].name);
        }
        if (callback) {
          callback();
        }
      }
    );
  }
  $(document).ready(function() {
    $("#restaurant_ac").autocomplete({
      delay: 0,
      source: function(req, responseFn) {
        requestData(function() {
          responseFn(r_names);
        });
      },
      select: function(value, data) {
        for (i in r_data) {
          restaurant = data.item.value;
          if (r_data[i].name == restaurant) {
            restaurant_data = r_data[i];
            $("#rid").val(r_data[i].id);
          }
        }
      }
    });
  });