config/routes.rb
Munchable::Application.routes.draw do
  devise_for :users,
    :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout',
      :sign_up => 'signup'
    }

  
  root :to => "application#index"
  resources :restaurants do
    get 'instant', :on => :collection, :action => 'instant'
    get 'n_instant', :on => :collection, :action => 'name_instant'
  end
  resources :categories do
    get 'autocomplete', :on => :collection, :action => 'autocomplete'
  end
  resources :locations
  resources :users do
    resources :groups do
      resource :list do
        resources :listings
      end
    end
    resource :profile
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :manage, User, :id => user.id
      can :manage, [Profile, Group, List, Listing], :user_id => user.id
    end
    can :create, User
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  belongs_to :list
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_one :list

  def members
    uids = self.memberships.all(:select => :user_id).collect {|m| m.user_id }.uniq
    User.all(:conditions => "id IN (#{uids.join(',')})")
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  has_many :listings, :dependent => :destroy
  has_many :restaurants, :through => :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :list
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :restaurants

  @zone = "? > x_lower AND ? < x_upper AND ? > y_lower AND ? < y_upper"

  def self.get_location(x, y)
    self.where(@zone, x, x, y, y).first
  end

  def bounds
    {'x' => [x_lower, x_upper], 'y' => [y_lower, y_upper]}
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :location
  has_many :menu_items
  has_many :menu_comments
  has_many :comments
  has_many :listings, :dependent => :destroy
  has_many :lists, :through => :listings

  scope :within_bounds_xy, lambda {|bounds|
    where('x > ? AND x < ? AND y > ? AND y < ?',
      bounds['x'][0], bounds['x'][1], bounds['y'][0], bounds['y'][1]
    )
  }
  scope :within_bounds, lambda {|bounds|
    where('xy && ?', Polygon.from_coordinates([[
      [bounds['x'][0], bounds['y'][0]],
      [bounds['x'][1], bounds['y'][0]],
      [bounds['x'][1], bounds['y'][1]],
      [bounds['x'][0], bounds['y'][1]],
      [bounds['x'][0], bounds['y'][0]]
    ]], 4326))
  }
  scope :k_nearest, lambda {|center, k|
    if center.all? {|c| c.is_a? Numeric}
      order("ST_Distance(xy, ST_GeomFromText('#{'POINT(%f %f)' % center}', 4326))").limit(k)
    end
  }
  scope :relevant, lambda {|category|
    where("categories LIKE ?", ["%#{category}%"])
  }
  scope :limited, lambda { |k|
    order('rating DESC, review_count DESC').limit(k)
  }
  scope :tsearch, lambda { |query|
    where("to_tsvector('english', name) @@ to_tsquery('english', E?)", query.split.join(' & '))
  }

  def self.get_nearest(bounds, center, category, max_num)
    self.relevant(category)
      .within_bounds(bounds)
      .k_nearest(center, max_num)
  end

  def self.get_best(bounds, category, max_num)
    self.relevant(category)
      .within_bounds(bounds)
      .limited(max_num)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  validates_presence_of  :password

  has_one :profile
  has_many :memberships, :dependent => :destroy
  has_many :groups, :through => :memberships
  has_many :lists, :through => :groups
  has_many :comments

  after_create :create_profile

  def create_group(name)
    g = Group.new({
      :user_id => self.id,
      :name => name,
    })
    if g.save
      Membership.create({
        :user_id => self.id,
        :group_id => g.id,
        :role => 'admin'
      })
      List.create({
        :user_id => self.id,
        :group_id => g.id
      })
      g
    else
      nil
    end
  end

  def create_profile
    Profile.create({
      :user_id => self.id
    })
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @location = Location.find(params[:location_id])
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.where(:location_id => @location.id)
  end

  def autocomplete
    categories = Category.search(:name_starts_with => params[:query])
    render :json => { :query => params[:query], :suggestions => categories.relation.collect{|c| c.name} }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    @group = @user.create_group(params[:group_name])

    respond_to do |format|
      format.js
    end
  end

  def show
    @user = User.find(params[:user_id])
    @group = Group.find(params[:id])
    @list = @group.list

    @restaurant_listings = @list.listings.zip(@list.restaurants)
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    @group = Group.find(params[:group_id])
    @restaurant = Restaurant.find(params[:rid])

    if Listing.where(:list_id => @group.list.id, :restaurant_id => @restaurant.id).empty?
      @listing = Listing.create({
        :list_id => @group.list.id,
        :restaurant_id => @restaurant.id
      })
    else
      flash[:notice] = 'Restaurant already exists!'
    end
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def show
  end
  
  def update
    rid = params[:rid]
    name = params[:q]

    restaurant = Restaurant.find(params[:rid])
    if restaurant
      list = List.where(:group_id => params[:group_id]).first
      list.restaurants << restaurant
      list.save
      render :json => {
        :name => restaurant.name,
        :address => restaurant.address,
        :hours => restaurant.hours,
        :website => restaurant.website,
        :rating => restaurant.rating,
        :review_count => restaurant.review_count,
        :take_out => restaurant.take_out,
        :delivery => restaurant.delivery,
        :x => restaurant.xy.x,
        :y => restaurant.xy.y
      }
    else
      render :json => 0
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    @location = Location.find(params[:id])
    @categories = Category.all.collect {|c| c.name }
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = User.find(params[:user_id])
    authorize! :manage, @user.profile
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def new
  end

end

app/controllers/yelp_controller.rb
class YelpController < ApplicationController
  def index
    serializer = ActiveSupport::JSON
    @restaurants = Yelp.find(:all, :limit => "10")
    @restaurants_serialized = serializer.encode(@restaurants)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    // = stylesheet_link_tag 'compiled/print.css', :media => 'print'
    /[if lt IE 8]
      = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
    = stylesheet_link_tag 'compiled/style.css', :media => 'screen'
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    // = javascript_include_tag 'jquery.tablesorter.min.js'
    = javascript_include_tag 'jquery-ui-1.8.5.custom.min.js'

  %body.bp.main
    #container
      #header
        #logo
          = link_to image_tag('/images/logo.png'), root_url
          -# %h1= link_to 'Most Munchable', root_url
        -#
          #navbar
            - if user_signed_in?
              = link_to 'Your Profile', user_profile_url(:user_id => current_user.id)
              #{current_user.email}
              &nbsp;-&nbsp;
              = link_to 'Logout', destroy_user_session_url
            - else
              = link_to 'Login', new_user_session_url
              &nbsp;-&nbsp;
              = link_to 'Create Account', new_user_registration_url
            %br/
      #content
        #notices
          - if flash[:error]
            .error= flash[:error]
          - else
            .error{:style => 'display: none'}
          - if flash[:notice]
            .notice= flash[:notice]
          - else
            .notice{:style => 'display: none'}
          - if flash[:success]
            .success= flash[:success]
          - else
            .success{:style => 'display: none'}
        .clear
        %br/
        =yield
      #footer

app/views/shared/_simple_table.html.haml
%b#category= @category
%table.tablesorter#results_table
  %thead
    %tr
      %th{:style => "width: 10%"} Rank
      %th{:style => "width: 45%"} Name
      %th{:style => "width: 10%"} Rating
      %th{:style => "width: 10%"} Reviews
      %th{:style => "width: 15%"} Take Out?
      %th{:style => "width: 10%"} Delivery?
  %tbody
    - @restaurants.each_with_index do |restaurant, i|
      %tr
        %td= i+1
        %td= restaurant.name
        - if restaurant.rating >= 4.5
          %td.green= restaurant.rating
        - elsif restaurant.rating >= 4
          %td.orange= restaurant.rating
        - else
          %td.red= restaurant.rating
        %td= restaurant.review_count
        - if restaurant.take_out
          %td.green yes
        - else
          %td.red no
        - if restaurant.delivery
          %td.green yes
        - else
          %td.red no